apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-trusted-to-db
  namespace: production
spec:
  selector: app == 'db'
  types: 
  - Ingress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: role == 'trusted'
    destination:
      ports:
      - 5432